environment:
  matrix:
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"

install:
    - cmd: |
        choco install maven
        refreshenv
        where mvn
        cd C:\projects\arquillian-liberty-dependencies

build_script:
      - "mvn clean install"
      - "mvn verify -Pit -U"
      - "cd gradle-tests & gradlew.bat clean build -i -s" 
test: off
